export const EVENTS = Object.freeze({
  CONNECT: "CONNECT",
  DISCONNECT: "DISCONNECT",

  JOIN: "JOIN",
  LEAVE: "LEAVE",

  SEND_CHANGES: "SEND-CHANGES",
  RECEIVE_CHANGES: "RECEIVE-CHANGES",

  SEND_CURSOR_MOVEMENT: "SEND-CURSOR-MOVEMENT",
  RECEIVE_CURSOR_MOVEMENT: "RECEIVE_CURSOR_MOVEMENT",

  SEND_MESSAGE: "SEND-MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE-MESSAGE",

  ERROR: "ERROR",
});
